# Generated by Django 2.0.2 on 2018-08-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFLteams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfl_team',
            name='qb_Playoff',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='nfl_team',
            name='rb_Playoff',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='nfl_team',
            name='te_Playoff',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='nfl_team',
            name='wr_Playoff',
            field=models.IntegerField(default=-1),
        ),
    ]
