# Generated by Django 2.0.2 on 2018-08-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NFLteams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=-1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NFLteams.NFL_Team')),
            ],
        ),
    ]
