# Generated by Django 2.0.2 on 2018-08-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='positionRank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=5),
        ),
    ]
