# Generated by Django 2.0.2 on 2018-07-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('usrEmail', models.TextField()),
                ('usrPassword', models.CharField(max_length=25)),
                ('usrName', models.CharField(max_length=25)),
            ],
        ),
    ]
